version: '3'
services:
  gradle:
    build: ./
    #image: gradle
    container_name: gradle
  jenkins:
    ports: 
      - "8098:8080"
      - "50000:50000"
    image: jenkins/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: {}